services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgresql://pgadmin:1234@db:5432/digital_wallet
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: digital_wallet_db
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: digital_wallet
    ports:
      - '6432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
